name: Spring Boot CI/CD

# Trigger the workflow on any push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Set up jobs
jobs:
  build:
    # The environment where the job will run
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Check out the code
      uses: actions/checkout@v2

    # Step 2: Set up JDK (Java 17 in this case)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build the project with Maven
    - name: Build with Maven
      run: mvn clean install

    # Step 5: Run the tests
    - name: Run tests
      run: mvn test